(function(_ds){var window=this;var K1=function(a,b){b="translate3d("+b+"px,0px,0px)";_ds.km(a,J1(),b)},J1=_ds.Bi(function(){return _ds.bf&&9==_ds.xf?"-ms-transform":"transform"});var N1=function(a){a.h=L1(a,".devsite-top-logo-row-wrapper-wrapper");a.g=L1(a,".devsite-collapsible-section");a.o=L1(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",`${a.h}`);a.setAttribute("bottom-row--height",`${a.g}`);a.setAttribute("bottom-tabs--height",`${a.o}`);a.style.setProperty("--devsite-js-top-row--height",`${a.h}px`);a.style.setProperty("--devsite-js-bottom-row--height",`${a.g}px`);a.style.setProperty("--devsite-js-bottom-tabs--height",`${a.o}px`);M1(a)},M1=function(a){const b=
a.querySelector(".devsite-collapsible-section");a.offset>=a.g&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.offset<a.g-a.o&&a.hasAttribute("bottom-row--hidden")&&a.removeAttribute("bottom-row--hidden");b&&a.offset!==a.oa&&(_ds.km(b,"transform",`translate3d(0, -${a.offset}px, 0)`),O1(a),a.oa=a.offset);document.body.style.setProperty("--devsite-js-header-height",`${a.v()}px`)},P1=function(a){var b=a.querySelector(".devsite-top-logo-row-middle");const c=a.querySelector("devsite-search"),
d=a.querySelector(".devsite-search-background");if(b&&c&&d){_ds.H(a.qa);a.ea&&window.cancelAnimationFrame(a.ea);c.removeAttribute("transition");a.removeAttribute("search-expanded");var e=new _ds.Oi(b.offsetWidth,b.offsetHeight);b=new _ds.Oi(c.offsetWidth,c.offsetHeight);var f=_ds.Dm(c),g="rtl"===document.documentElement.getAttribute("dir")?1:-1,h=(e.width-f.left-f.right)/b.width;e=(e.width-(b.width+f.left+f.right))*g;var k=(f=a.hasAttribute("search-active"))?e:0,l=f?h:1;_ds.km(d,{opacity:1,width:`${b.width}px`,
height:`${b.height}px`});K1(c,a.hasAttribute("search-active")?0:e);_ds.em(a.qa,d,_ds.xg,()=>{const m=a.querySelector("devsite-search"),n=a.querySelector(".devsite-search-background");n&&(n.style.opacity="0");m&&(m.removeAttribute("transition"),K1(m,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});a.ea=window.requestAnimationFrame(()=>{c.setAttribute("transition","");var m="scale3d("+l+",1,1)";_ds.km(d,J1(),m);K1(c,k)})}},Q1=async function(a,
b){if(a.hasAttribute("billboard")){var c=a.querySelector("devsite-search"),d=a.querySelector("devsite-search input.devsite-search-query");a=a.querySelector(".devsite-header-billboard-search devsite-search");var e=null==a?void 0:a.querySelector("input.devsite-search-query");c&&d&&a&&e&&(b?(c.removeAttribute("disabled"),document.activeElement===e&&(await _ds.Ok(),d.focus()),a.setAttribute("disabled","")):(a.removeAttribute("disabled"),document.activeElement===d&&e.focus(),c.setAttribute("disabled",
"")))}},S1=function(a){a.eventHandler.listen(a,"devsite-search-toggle",b=>{b=b.Fa;_ds.Kj(b.target,null,"devsite-top-logo-row-middle")&&(b.detail.active?a.setAttribute("search-active",""):a.removeAttribute("search-active"))});a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>document.body.removeAttribute("devsite-book-nav--open"));a.eventHandler.listen(window,"resize",()=>R1(a));a.eventHandler.listen(document.body,["devsite-page-loaded","devsite-content-updated"],()=>{R1(a)});a.eventHandler.listen(a,
"click",b=>{b.defaultPrevented||"devsite-hamburger-menu"!==b.target.getAttribute("id")||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",{bubbles:!0})))})},T1=function(a){if(!a.querySelector(".devsite-search-background")&&(a=a.querySelector(".devsite-top-logo-row-middle"))){const b=document.createElement("div");b.classList.add("devsite-search-background");b.style.opacity="1";a.appendChild(b)}},O1=
function(a){0===a.g?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},R1=function(a){window.requestAnimationFrame(()=>a.va.Oa())},L1=function(a,b){return(a=a.querySelector(b))?a.getBoundingClientRect().height:0},U1=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=0;c<a.attributes.length;++c)d=
a.attributes.item(c),b.setAttribute(d.name,d.value)},V1=function(a,b,c){b=b.querySelector(c);c=a.querySelector(c);b&&c&&(a.updated=!0,_ds.qi(a,c,b))},W1=class extends _ds.E{constructor(){super(...arguments);this.eventHandler=new _ds.G;this.oa=-1;this.qa=new _ds.G;this.ea=0;this.ma=new MutationObserver(()=>N1(this));this.va=new _ds.am(()=>{N1(this);O1(this)},15);this.authUser=void 0;this.offset=this.o=this.g=this.h=0;this.updated=!1}static get observedAttributes(){return["offset","search-active","bottom-row--hidden"]}attributeChangedCallback(a,
b,c){switch(a){case "offset":this.offset=Number(this.getAttribute("offset")||"")||0;M1(this);break;case "search-active":P1(this);break;case "bottom-row--hidden":a=null!==c,b=this.querySelector("devsite-search input.devsite-search-query"),c=this.querySelector(".devsite-header-billboard-search devsite-search input.devsite-search-query"),b&&c&&(a?b.value=c.value:c.value=b.value),Q1(this,a)}}connectedCallback(){S1(this);T1(this);O1(this);N1(this);this.ma.observe(this,{childList:!0,subtree:!0});M1(this);
const a=_ds.F();this.authUser=_ds.ok(_ds.pk(a.href),"authuser")}disconnectedCallback(){_ds.H(this.eventHandler);this.ma.disconnect()}v(){return this.h+this.g-this.offset}ua(){return this.h+this.g}Wb(a){this.updated=!1;if(a){V1(this,a,".devsite-header-upper-tabs");V1(this,a,".devsite-collapsible-section");V1(this,a,".devsite-product-name-wrapper");V1(this,a,"devsite-language-selector");V1(this,a,"devsite-shell-activate-button");var b=a.querySelector("devsite-search"),c=this.querySelector("devsite-search");
b&&c&&U1(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");c&&b&&(U1(c,b),c=_ds.F(),c=_ds.ok(_ds.pk(c.href),"authuser"),c!==this.authUser&&(this.authUser=c,b.refresh()));_ds.qi(this,this.querySelector("cloudx-additional-tabs"),a.querySelector("cloudx-additional-tabs"),this.querySelector(".devsite-top-logo-row-middle"));_ds.qi(this,this.querySelector(".devsite-header-link"),a.querySelector(".devsite-header-link"),this.querySelector("devsite-language-selector"))}!this.updated&&
a&&(_ds.qj(this),this.appendChild(a));T1(this);R1(this)}};try{window.customElements.define("devsite-header",W1)}catch(a){console.warn("devsite.app.customElement.DevsiteHeader",a)};})(_ds_www);
