(function(_ds){var window=this;var vca=function(a){const b=a.Qn,c=a.hd,d=a.uu;a=a.Kv;let e;e='<ul class="devsite-nav-list"><li class="devsite-nav-item devsite-nav-heading devsite-toc-toggle" role="heading" aria-level="2"><span class="devsite-nav-title"><span class="devsite-nav-text">On this page</span></span>';c&&(e=e+'<button type="button" title="'+_ds.Gz("Expand/collapse contents"),e+='" class="devsite-nav-show-all button-transparent material-icons"></button>');e+="</li>";const f=b.length;for(let h=0;h<f;h++){var g=b[h];e+='<li class="devsite-nav-item"'+
(c&&g.index<a?" visible":"")+'><a href="#'+_ds.Y(g.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.Y(h)+'" track-type="navigation" track-name="'+(c?"embeddedNav":"rightNav")+'" track-metadata-position="'+_ds.Y(h)+'" track-metadata-link-destination="#'+_ds.Y(g.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.T(g.text)+"</span></a>";if(_ds.U(g.children).length){e+='<ul class="devsite-nav-list">';
g=g.children;const k=g.length;for(let l=0;l<k;l++){const m=g[l];e+='<li class="devsite-nav-item"'+(c&&m.index<a?" visible":"")+'><a href="#'+_ds.Y(m.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.Y(h)+"."+_ds.Y(l)+'" track-type="navigation" track-name="'+(c?"embeddedNav":"rightNav")+'" track-metadata-position="'+_ds.Y(h)+"."+_ds.Y(l)+'" track-metadata-link-destination="#'+
_ds.Y(m.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.T(m.text)+"</span></a></li>"}e+="</ul>"}e+="</li>"}d&&(e=c?e+'<li class="devsite-nav-item devsite-apix-link"><a href="#try-it" class="devsite-nav-title"><span class="devsite-nav-text" tooltip>Try it</span></a></li>':e+'<button type="button" class="devsite-show-apix button-primary">Try it!</button>');c&&(e=e+'<li class="devsite-toc-toggle"><button type="button" class="button-flat devsite-nav-more-items material-icons" track-type="navigation" track-name="embeddedNavExpand" title="'+
_ds.Gz("Expand/collapse contents"),e+='"></button></li>');return(0,_ds.Q)(e+"</ul>")};var B8=function(a){if(!a.hasAttribute("disabled")){var b=document.querySelector("devsite-content .devsite-article-body");b?(a.hd?a.classList.add("devsite-toc-embedded"):a.classList.add("devsite-toc"),wca(a,b),a.qa=!0):a.Db()}},yca=async function(a){await xca(a);if(a.g){var b=`#${a.g.id}`,c=encodeURI(b);b=a.ea.get(b)||a.ea.get(c);a.o!==b&&(a.o&&a.o.classList.remove("devsite-nav-active"),b&&(b.classList.add("devsite-nav-active"),a.ma&&("scrollIntoViewIfNeeded"in b?b.scrollIntoViewIfNeeded():b.scrollIntoView()),
a.o=b))}},zca=function(a){a.hd||a.eventHandler.listen(document.body,"devsite-content-updated devsite-element-hidden devsite-element-visible devsite-page-loaded devsite-sticky-resize devsite-sticky-scroll".split(" "),()=>{a.ra.Oa()});a.eventHandler.listen(document.body,"devsite-content-updated",()=>{B8(a)})},Aca=async function(a){if("IntersectionObserver"in _ds.kj()){a.dc&&a.dc.disconnect();var b=document.querySelector("devsite-header");let c=152;b&&(await window.customElements.whenDefined("devsite-header"),
(b=Number(b.getAttribute("top-row--height"))+Number(b.getAttribute("bottom-row--height")))&&(c=b));a.dc=new IntersectionObserver(d=>{for(const e of d)e.isIntersecting?a.v.add(e.target):a.v.delete(e.target);a.ra.Oa()},{rootMargin:`${c}px 0px 0px 0px`,threshold:[0,1]})}a.ua.g()},xca=async function(a){let b=0;var c=document.querySelector("devsite-header");c&&(await window.customElements.whenDefined("devsite-header"),b=c.v());c=a.h.findIndex(e=>a.v.has(e)&&e.getBoundingClientRect().top>=b);const d=a.h[c];
if(d){const e=await Bca();d.getBoundingClientRect().top-b>e&&0<c?a.g=a.h[c-1]:a.g=d}else a.g&&a.g.getBoundingClientRect().top>window.innerHeight&&(c=a.h.indexOf(a.g),0<c&&(a.g=a.h[c-1]))},wca=function(a,b){const c=[];let d=!1,e="";switch(a.getAttribute("depth")){case "1":e="h2:not(.hide-from-toc):not(#contents):not(#table-of-contents)";break;default:e="h2:not(.hide-from-toc):not(#contents):not(#table-of-contents), h3:not(.hide-from-toc):not(#contents):not(#table-of-contents)"}a.h=[...b.querySelectorAll(e)].filter(f=>
f.id&&f.dataset.text).filter(f=>Cca(f));for(const [f,g]of a.h.entries())b=g,b={id:b.id,level:b.tagName.toLowerCase(),text:b.dataset.text,children:[],index:f},"h2"===b.level?(c.push(b),d=!0):d?c[c.length-1].children.push(b):c.push(b);_ds.ub(a.oa,c,a.va.bind(a))&&a.qa||(c.length?(Dca(a,c),a.show(),a.hd||Eca(a)):a.Db(),a.oa=c)},Cca=function(a){return _ds.bl.find(b=>!!_ds.Kj(a,null,b,6))||_ds.Kj(a,"devsite-selector",null,6)||_ds.Kj(a,null,"devsite-dialog",3)?!1:!0},Dca=function(a,b){const c=_ds.L(vca,
{Qn:b,hd:a.hd,uu:!!document.body.querySelector("devsite-apix, .devsite-apix"),Kv:8>b.length?8:5});b=c.querySelectorAll("a.devsite-nav-title");for(const d of b){b=d;const e=b.hash,f=encodeURI(b.hash);a.ea.set(e,b);a.ea.set(f,b)}_ds.qj(a);a.hd&&_ds.D(a,"hidden","",c);a.appendChild(c);if(a.hd){if(8<a.getElementsByClassName("devsite-nav-item").length){for(const d of a.querySelectorAll(".devsite-nav-show-all, .devsite-nav-more-items"))a.eventHandler.listen(d,"click",()=>{a.hasAttribute("expanded")?a.removeAttribute("expanded"):
_ds.D(a,"expanded","")});_ds.D(a,"expandable","")}else a.removeAttribute("expandable");setTimeout(()=>{c.removeAttribute("hidden")},0)}},Eca=async function(a){await a.ua.promise;if(a.dc){a.dc.disconnect();a.v.clear();a.o&&a.o.classList.remove("devsite-nav-active");a.o=null;for(const b of a.h)a.dc.observe(b)}},Bca=async function(){let a=0,b=0;const c=document.querySelector("devsite-header");c&&(await window.customElements.whenDefined("devsite-header"),a=c.v(),b=c.ua());return Math.max(b-a,Math.floor((window.innerHeight-
a)/5))},C8=class extends _ds.E{static get observedAttributes(){return["max-height","offset"]}constructor(){super();this.eventHandler=new _ds.G;this.ua=new _ds.gm;this.v=new Set;this.ea=new Map;this.xa=new _ds.am(()=>void B8(this),16);this.ra=new _ds.am(()=>void yca(this),33);this.g=this.o=null;this.h=[];this.qa=!1;this.dc=null;this.ma=this.hd=!1;this.oa=[];_ds.ni(this,(0,_ds.r)`disabled`,(0,_ds.r)`has-sidebar`,(0,_ds.r)`hidden`,(0,_ds.r)`expandable`,(0,_ds.r)`expanded`,(0,_ds.r)`visible`)}connectedCallback(){this.hd=
this.hasAttribute("devsite-toc-embedded");this.ma=document.body.hasAttribute("concierge");B8(this);zca(this)}disconnectedCallback(){this.Db();this.qa=!1;_ds.H(this.eventHandler)}Kj(a){a=a&&"false"===a.toLowerCase();this.oa=[];_ds.qj(this);a?(_ds.D(this,"disabled",""),this.Db()):(this.removeAttribute("disabled"),this.show(),this.xa.Oa())}Db(){_ds.qj(this);this.dispatchEvent(new CustomEvent("devsite-element-hidden",{bubbles:!0}));this.removeAttribute("visible");_ds.D(this,"hidden","");if(!this.hd&&
!this.ma){const a=document.querySelector(".devsite-main-content");a&&a.removeAttribute("has-sidebar")}}show(){this.dispatchEvent(new CustomEvent("devsite-element-visible",{bubbles:!0}));this.removeAttribute("hidden");_ds.D(this,"visible","");if(!this.hd){const a=document.querySelector(".devsite-main-content");a&&_ds.D(this,"has-sidebar","",a);Aca(this)}}va(a,b){let c=!0;if(a.children.length||b.children.length)c=_ds.ub(a.children,b.children,this.va.bind(this));return c&&a.id===b.id&&a.text===b.text}};
C8.prototype.renderUpdatedContent=C8.prototype.Kj;C8.prototype.disconnectedCallback=C8.prototype.disconnectedCallback;C8.prototype.connectedCallback=C8.prototype.connectedCallback;try{window.customElements.define("devsite-toc",C8)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteToc",a)};})(_ds_www);
